### ISSUE TITLE
Typo in Logix Wizard popup

### ISSUE THREAD

**Issue by cblanken** [dagryl/plc-simulator-docs#7]
I noticed a typo in the Logix Wizzard popup "answear" instead of "answer".

![image](https://github.com/dagryl/plc-simulator-docs/assets/155463130/41ad61e3-eaac-4dd2-b028-37a40ad4a15e)

I also wanted to use this issue as a chance to recommend you _don't_ push an AI LLM for PLC programming help. Since they are inherently unreliable, I feel it sets a bad precedent for any newcomers using the app.

**Comment by dagryl** [comment]
LLMs for PLCs are unreliable because there is not enough data online to train them properly. This is why I'm working on a fine-tuned GPT model so that we can all use these incredible tools in our PLC world. :)
